"""fix payment relationship

Revision ID: 0aaab8f2d24d
Revises: df4c8af9e0cc
Create Date: 2025-10-27 05:25:59.234635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0aaab8f2d24d'
down_revision: Union[str, Sequence[str], None] = 'df4c8af9e0cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
