"""add_comments_to_models

Revision ID: ab4f2464ce2d
Revises: 1af9c2857b29
Create Date: 2025-11-20 01:45:29.533088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ab4f2464ce2d'
down_revision: Union[str, Sequence[str], None] = '1af9c2857b29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_roles_id', table_name='roles')
    op.drop_table('roles')
    op.alter_column('order_items', 'id',
               existing_type=sa.INTEGER(),
               comment='Identificador único do item do pedido',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('order_items', 'order_id',
               existing_type=sa.INTEGER(),
               comment='ID do pedido relacionado',
               existing_nullable=True)
    op.alter_column('order_items', 'product_id',
               existing_type=sa.INTEGER(),
               comment='ID do produto comprado',
               existing_nullable=True)
    op.alter_column('order_items', 'quantity',
               existing_type=sa.INTEGER(),
               comment='Quantidade comprada',
               existing_nullable=False)
    op.alter_column('order_items', 'unit_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Preço unitário no momento da compra',
               existing_nullable=False)
    op.alter_column('orders', 'id',
               existing_type=sa.INTEGER(),
               comment='Identificador único do pedido',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('orders_id_seq'::regclass)"))
    op.alter_column('orders', 'user_id',
               existing_type=sa.INTEGER(),
               comment='ID do usuário que fez o pedido',
               existing_nullable=True)
    op.alter_column('orders', 'total_value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Valor total do pedido',
               existing_nullable=True)
    op.alter_column('orders', 'status',
               existing_type=sa.VARCHAR(length=50),
               comment='Status do pedido (pending, paid, shipped, etc.)',
               existing_nullable=True)
    op.alter_column('orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Data e hora de criação do pedido',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('orders', 'payment_method',
               existing_type=sa.VARCHAR(length=50),
               comment='Método de pagamento escolhido',
               existing_nullable=True)
    op.alter_column('prescriptions', 'id',
               existing_type=sa.INTEGER(),
               comment='Identificador único da receita',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('prescriptions', 'order_item_id',
               existing_type=sa.INTEGER(),
               comment='ID do item do pedido associado',
               existing_nullable=True)
    op.alter_column('prescriptions', 'doctor_name',
               existing_type=sa.VARCHAR(),
               comment='Nome do médico prescritor',
               existing_nullable=False)
    op.alter_column('prescriptions', 'crm',
               existing_type=sa.VARCHAR(),
               comment='CRM do médico',
               existing_nullable=False)
    op.alter_column('prescriptions', 'file_path',
               existing_type=sa.VARCHAR(),
               comment='Caminho do arquivo da receita (upload)',
               existing_nullable=False)
    op.alter_column('prescriptions', 'issued_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Data de emissão/upload da receita',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('products', 'id',
               existing_type=sa.INTEGER(),
               comment='Identificador único do produto',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('products_id_seq'::regclass)"))
    op.alter_column('products', 'name',
               existing_type=sa.VARCHAR(length=120),
               comment='Nome do produto',
               existing_nullable=False)
    op.alter_column('products', 'category',
               existing_type=sa.VARCHAR(length=100),
               comment='Categoria do produto (ex: Medicamento, Higiene)',
               existing_nullable=True)
    op.alter_column('products', 'barcode',
               existing_type=sa.VARCHAR(length=100),
               comment='Código de barras do produto',
               existing_nullable=True)
    op.alter_column('products', 'description',
               existing_type=sa.VARCHAR(),
               comment='Descrição detalhada do produto',
               existing_nullable=True)
    op.alter_column('products', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Preço unitário do produto',
               existing_nullable=False)
    op.alter_column('products', 'stock_quantity',
               existing_type=sa.INTEGER(),
               comment='Quantidade em estoque',
               existing_nullable=True)
    op.alter_column('products', 'validity',
               existing_type=sa.DATE(),
               comment='Data de validade do produto',
               existing_nullable=True)
    op.alter_column('products', 'stripe',
               existing_type=sa.VARCHAR(length=100),
               comment='Tarja do medicamento (ex: Preta, Vermelha)',
               existing_nullable=True)
    op.alter_column('products', 'requires_prescription',
               existing_type=sa.BOOLEAN(),
               comment='Indica se requer receita médica',
               existing_nullable=True)
    op.alter_column('user_roles', 'id',
               existing_type=sa.INTEGER(),
               comment='Identificador único do papel',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('user_roles_id_seq'::regclass)"))
    op.alter_column('user_roles', 'name',
               existing_type=sa.VARCHAR(length=50),
               comment='Nome do papel (ex: admin, pharmacist)',
               existing_nullable=False)
    op.alter_column('user_roles', 'description',
               existing_type=sa.VARCHAR(length=255),
               comment='Descrição das permissões do papel',
               existing_nullable=True)
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               comment='Identificador único do usuário',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment='Nome completo do usuário',
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=100),
               comment='Endereço de email do usuário',
               existing_nullable=False)
    op.alter_column('users', 'cpf',
               existing_type=sa.VARCHAR(length=14),
               comment='CPF do usuário',
               existing_nullable=True)
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=20),
               comment='Telefone de contato',
               existing_nullable=True)
    op.alter_column('users', 'address',
               existing_type=sa.VARCHAR(length=255),
               comment='Endereço completo',
               existing_nullable=True)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               comment='Hash da senha do usuário',
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Indica se o usuário está ativo',
               existing_nullable=True)
    op.alter_column('users', 'role_id',
               existing_type=sa.INTEGER(),
               comment='ID do papel (role) do usuário',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='ID do papel (role) do usuário',
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Indica se o usuário está ativo',
               existing_nullable=True)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Hash da senha do usuário',
               existing_nullable=False)
    op.alter_column('users', 'address',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Endereço completo',
               existing_nullable=True)
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Telefone de contato',
               existing_nullable=True)
    op.alter_column('users', 'cpf',
               existing_type=sa.VARCHAR(length=14),
               comment=None,
               existing_comment='CPF do usuário',
               existing_nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Endereço de email do usuário',
               existing_nullable=False)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Nome completo do usuário',
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Identificador único do usuário',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('user_roles', 'description',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Descrição das permissões do papel',
               existing_nullable=True)
    op.alter_column('user_roles', 'name',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Nome do papel (ex: admin, pharmacist)',
               existing_nullable=False)
    op.alter_column('user_roles', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Identificador único do papel',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('user_roles_id_seq'::regclass)"))
    op.alter_column('products', 'requires_prescription',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Indica se requer receita médica',
               existing_nullable=True)
    op.alter_column('products', 'stripe',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Tarja do medicamento (ex: Preta, Vermelha)',
               existing_nullable=True)
    op.alter_column('products', 'validity',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Data de validade do produto',
               existing_nullable=True)
    op.alter_column('products', 'stock_quantity',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Quantidade em estoque',
               existing_nullable=True)
    op.alter_column('products', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='Preço unitário do produto',
               existing_nullable=False)
    op.alter_column('products', 'description',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Descrição detalhada do produto',
               existing_nullable=True)
    op.alter_column('products', 'barcode',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Código de barras do produto',
               existing_nullable=True)
    op.alter_column('products', 'category',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Categoria do produto (ex: Medicamento, Higiene)',
               existing_nullable=True)
    op.alter_column('products', 'name',
               existing_type=sa.VARCHAR(length=120),
               comment=None,
               existing_comment='Nome do produto',
               existing_nullable=False)
    op.alter_column('products', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Identificador único do produto',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('products_id_seq'::regclass)"))
    op.alter_column('prescriptions', 'issued_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Data de emissão/upload da receita',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('prescriptions', 'file_path',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Caminho do arquivo da receita (upload)',
               existing_nullable=False)
    op.alter_column('prescriptions', 'crm',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='CRM do médico',
               existing_nullable=False)
    op.alter_column('prescriptions', 'doctor_name',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Nome do médico prescritor',
               existing_nullable=False)
    op.alter_column('prescriptions', 'order_item_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='ID do item do pedido associado',
               existing_nullable=True)
    op.alter_column('prescriptions', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Identificador único da receita',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('orders', 'payment_method',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Método de pagamento escolhido',
               existing_nullable=True)
    op.alter_column('orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Data e hora de criação do pedido',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('orders', 'status',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Status do pedido (pending, paid, shipped, etc.)',
               existing_nullable=True)
    op.alter_column('orders', 'total_value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Valor total do pedido',
               existing_nullable=True)
    op.alter_column('orders', 'user_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='ID do usuário que fez o pedido',
               existing_nullable=True)
    op.alter_column('orders', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Identificador único do pedido',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('orders_id_seq'::regclass)"))
    op.alter_column('order_items', 'unit_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Preço unitário no momento da compra',
               existing_nullable=False)
    op.alter_column('order_items', 'quantity',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Quantidade comprada',
               existing_nullable=False)
    op.alter_column('order_items', 'product_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='ID do produto comprado',
               existing_nullable=True)
    op.alter_column('order_items', 'order_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='ID do pedido relacionado',
               existing_nullable=True)
    op.alter_column('order_items', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Identificador único do item do pedido',
               existing_nullable=False,
               autoincrement=True)
    op.create_table('roles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='roles_pkey'),
    sa.UniqueConstraint('name', name='roles_name_key')
    )
    op.create_index('ix_roles_id', 'roles', ['id'], unique=False)
    # ### end Alembic commands ###
