"""Add client fields

Revision ID: e32329a3fadf
Revises: ab4f2464ce2d
Create Date: 2025-11-21 21:13:17.031344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e32329a3fadf'
down_revision: Union[str, Sequence[str], None] = 'ab4f2464ce2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('birth_date', sa.String(length=20), nullable=True, comment='Data de nascimento'))
    op.add_column('users', sa.Column('client_type', sa.String(length=50), nullable=True, comment='Tipo de cliente (regular, elderly, insurance)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'client_type')
    op.drop_column('users', 'birth_date')
    # ### end Alembic commands ###
